//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikSilverlightApp1.Web
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Etudiant
    {
        [DataMember]
        public int cne { get; set; }
        [DataMember]
        public string nom { get; set; }
        [DataMember]
        public string prenom { get; set; }
        [DataMember]
        public string email { get; set; }
        [DataMember]
        public Nullable<System.DateTime> date_naissance { get; set; }
        [DataMember]
        public string picture { get; set; }
        [DataMember]
        public Nullable<double> note { get; set; }
        [DataMember]
        public string filiere { get; set; }
        [DataMember]
        public virtual Filiere Filiere1 { get; set; }
    }
}
