//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace TelerikSilverlightApp1.ServiceReference3 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Etudiant", Namespace="http://schemas.datacontract.org/2004/07/TelerikSilverlightApp1.Web")]
    public partial class Etudiant : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TelerikSilverlightApp1.ServiceReference3.Filiere Filiere1Field;
        
        private int cneField;
        
        private System.Nullable<System.DateTime> date_naissanceField;
        
        private string emailField;
        
        private string filiereField;
        
        private string nomField;
        
        private System.Nullable<double> noteField;
        
        private string pictureField;
        
        private string prenomField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TelerikSilverlightApp1.ServiceReference3.Filiere Filiere1 {
            get {
                return this.Filiere1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Filiere1Field, value) != true)) {
                    this.Filiere1Field = value;
                    this.RaisePropertyChanged("Filiere1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cne {
            get {
                return this.cneField;
            }
            set {
                if ((this.cneField.Equals(value) != true)) {
                    this.cneField = value;
                    this.RaisePropertyChanged("cne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_naissance {
            get {
                return this.date_naissanceField;
            }
            set {
                if ((this.date_naissanceField.Equals(value) != true)) {
                    this.date_naissanceField = value;
                    this.RaisePropertyChanged("date_naissance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filiere {
            get {
                return this.filiereField;
            }
            set {
                if ((object.ReferenceEquals(this.filiereField, value) != true)) {
                    this.filiereField = value;
                    this.RaisePropertyChanged("filiere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> note {
            get {
                return this.noteField;
            }
            set {
                if ((this.noteField.Equals(value) != true)) {
                    this.noteField = value;
                    this.RaisePropertyChanged("note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string picture {
            get {
                return this.pictureField;
            }
            set {
                if ((object.ReferenceEquals(this.pictureField, value) != true)) {
                    this.pictureField = value;
                    this.RaisePropertyChanged("picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomField, value) != true)) {
                    this.prenomField = value;
                    this.RaisePropertyChanged("prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filiere", Namespace="http://schemas.datacontract.org/2004/07/TelerikSilverlightApp1.Web")]
    public partial class Filiere : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Etudiant> EtudiantsField;
        
        private string idField;
        
        private string nom_filiereField;
        
        private string responsableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Etudiant> Etudiants {
            get {
                return this.EtudiantsField;
            }
            set {
                if ((object.ReferenceEquals(this.EtudiantsField, value) != true)) {
                    this.EtudiantsField = value;
                    this.RaisePropertyChanged("Etudiants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_filiere {
            get {
                return this.nom_filiereField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_filiereField, value) != true)) {
                    this.nom_filiereField = value;
                    this.RaisePropertyChanged("nom_filiere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsable {
            get {
                return this.responsableField;
            }
            set {
                if ((object.ReferenceEquals(this.responsableField, value) != true)) {
                    this.responsableField = value;
                    this.RaisePropertyChanged("responsable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference3.MyService")]
    public interface MyService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:MyService/GetFilieresStats", ReplyAction="urn:MyService/GetFilieresStatsResponse")]
        System.IAsyncResult BeginGetFilieresStats(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.Dictionary<string, int> EndGetFilieresStats(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:MyService/GetAllStudents", ReplyAction="urn:MyService/GetAllStudentsResponse")]
        System.IAsyncResult BeginGetAllStudents(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<string>> EndGetAllStudents(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:MyService/DeleteStudent", ReplyAction="urn:MyService/DeleteStudentResponse")]
        System.IAsyncResult BeginDeleteStudent(string cne, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteStudent(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:MyService/getStudent", ReplyAction="urn:MyService/getStudentResponse")]
        System.IAsyncResult BegingetStudent(int cne, System.AsyncCallback callback, object asyncState);
        
        TelerikSilverlightApp1.ServiceReference3.Etudiant EndgetStudent(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:MyService/GetStudentsByFiliere", ReplyAction="urn:MyService/GetStudentsByFiliereResponse")]
        System.IAsyncResult BeginGetStudentsByFiliere(string filiere, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Etudiant> EndGetStudentsByFiliere(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:MyService/GetAllFilieres", ReplyAction="urn:MyService/GetAllFilieresResponse")]
        System.IAsyncResult BeginGetAllFilieres(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Filiere> EndGetAllFilieres(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServiceChannel : TelerikSilverlightApp1.ServiceReference3.MyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFilieresStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFilieresStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.Dictionary<string, int> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.Dictionary<string, int>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllStudentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllStudentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<string>> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<string>>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TelerikSilverlightApp1.ServiceReference3.Etudiant Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TelerikSilverlightApp1.ServiceReference3.Etudiant)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStudentsByFiliereCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStudentsByFiliereCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Etudiant> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Etudiant>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllFilieresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllFilieresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Filiere> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Filiere>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<TelerikSilverlightApp1.ServiceReference3.MyService>, TelerikSilverlightApp1.ServiceReference3.MyService {
        
        private BeginOperationDelegate onBeginGetFilieresStatsDelegate;
        
        private EndOperationDelegate onEndGetFilieresStatsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFilieresStatsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllStudentsDelegate;
        
        private EndOperationDelegate onEndGetAllStudentsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllStudentsCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteStudentDelegate;
        
        private EndOperationDelegate onEndDeleteStudentDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteStudentCompletedDelegate;
        
        private BeginOperationDelegate onBegingetStudentDelegate;
        
        private EndOperationDelegate onEndgetStudentDelegate;
        
        private System.Threading.SendOrPostCallback ongetStudentCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStudentsByFiliereDelegate;
        
        private EndOperationDelegate onEndGetStudentsByFiliereDelegate;
        
        private System.Threading.SendOrPostCallback onGetStudentsByFiliereCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllFilieresDelegate;
        
        private EndOperationDelegate onEndGetAllFilieresDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllFilieresCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetFilieresStatsCompletedEventArgs> GetFilieresStatsCompleted;
        
        public event System.EventHandler<GetAllStudentsCompletedEventArgs> GetAllStudentsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteStudentCompleted;
        
        public event System.EventHandler<getStudentCompletedEventArgs> getStudentCompleted;
        
        public event System.EventHandler<GetStudentsByFiliereCompletedEventArgs> GetStudentsByFiliereCompleted;
        
        public event System.EventHandler<GetAllFilieresCompletedEventArgs> GetAllFilieresCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TelerikSilverlightApp1.ServiceReference3.MyService.BeginGetFilieresStats(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFilieresStats(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.Dictionary<string, int> TelerikSilverlightApp1.ServiceReference3.MyService.EndGetFilieresStats(System.IAsyncResult result) {
            return base.Channel.EndGetFilieresStats(result);
        }
        
        private System.IAsyncResult OnBeginGetFilieresStats(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TelerikSilverlightApp1.ServiceReference3.MyService)(this)).BeginGetFilieresStats(callback, asyncState);
        }
        
        private object[] OnEndGetFilieresStats(System.IAsyncResult result) {
            System.Collections.Generic.Dictionary<string, int> retVal = ((TelerikSilverlightApp1.ServiceReference3.MyService)(this)).EndGetFilieresStats(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFilieresStatsCompleted(object state) {
            if ((this.GetFilieresStatsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFilieresStatsCompleted(this, new GetFilieresStatsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFilieresStatsAsync() {
            this.GetFilieresStatsAsync(null);
        }
        
        public void GetFilieresStatsAsync(object userState) {
            if ((this.onBeginGetFilieresStatsDelegate == null)) {
                this.onBeginGetFilieresStatsDelegate = new BeginOperationDelegate(this.OnBeginGetFilieresStats);
            }
            if ((this.onEndGetFilieresStatsDelegate == null)) {
                this.onEndGetFilieresStatsDelegate = new EndOperationDelegate(this.OnEndGetFilieresStats);
            }
            if ((this.onGetFilieresStatsCompletedDelegate == null)) {
                this.onGetFilieresStatsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFilieresStatsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFilieresStatsDelegate, null, this.onEndGetFilieresStatsDelegate, this.onGetFilieresStatsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TelerikSilverlightApp1.ServiceReference3.MyService.BeginGetAllStudents(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllStudents(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<string>> TelerikSilverlightApp1.ServiceReference3.MyService.EndGetAllStudents(System.IAsyncResult result) {
            return base.Channel.EndGetAllStudents(result);
        }
        
        private System.IAsyncResult OnBeginGetAllStudents(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TelerikSilverlightApp1.ServiceReference3.MyService)(this)).BeginGetAllStudents(callback, asyncState);
        }
        
        private object[] OnEndGetAllStudents(System.IAsyncResult result) {
            System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<string>> retVal = ((TelerikSilverlightApp1.ServiceReference3.MyService)(this)).EndGetAllStudents(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllStudentsCompleted(object state) {
            if ((this.GetAllStudentsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllStudentsCompleted(this, new GetAllStudentsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllStudentsAsync() {
            this.GetAllStudentsAsync(null);
        }
        
        public void GetAllStudentsAsync(object userState) {
            if ((this.onBeginGetAllStudentsDelegate == null)) {
                this.onBeginGetAllStudentsDelegate = new BeginOperationDelegate(this.OnBeginGetAllStudents);
            }
            if ((this.onEndGetAllStudentsDelegate == null)) {
                this.onEndGetAllStudentsDelegate = new EndOperationDelegate(this.OnEndGetAllStudents);
            }
            if ((this.onGetAllStudentsCompletedDelegate == null)) {
                this.onGetAllStudentsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllStudentsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllStudentsDelegate, null, this.onEndGetAllStudentsDelegate, this.onGetAllStudentsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TelerikSilverlightApp1.ServiceReference3.MyService.BeginDeleteStudent(string cne, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteStudent(cne, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void TelerikSilverlightApp1.ServiceReference3.MyService.EndDeleteStudent(System.IAsyncResult result) {
            base.Channel.EndDeleteStudent(result);
        }
        
        private System.IAsyncResult OnBeginDeleteStudent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cne = ((string)(inValues[0]));
            return ((TelerikSilverlightApp1.ServiceReference3.MyService)(this)).BeginDeleteStudent(cne, callback, asyncState);
        }
        
        private object[] OnEndDeleteStudent(System.IAsyncResult result) {
            ((TelerikSilverlightApp1.ServiceReference3.MyService)(this)).EndDeleteStudent(result);
            return null;
        }
        
        private void OnDeleteStudentCompleted(object state) {
            if ((this.DeleteStudentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteStudentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteStudentAsync(string cne) {
            this.DeleteStudentAsync(cne, null);
        }
        
        public void DeleteStudentAsync(string cne, object userState) {
            if ((this.onBeginDeleteStudentDelegate == null)) {
                this.onBeginDeleteStudentDelegate = new BeginOperationDelegate(this.OnBeginDeleteStudent);
            }
            if ((this.onEndDeleteStudentDelegate == null)) {
                this.onEndDeleteStudentDelegate = new EndOperationDelegate(this.OnEndDeleteStudent);
            }
            if ((this.onDeleteStudentCompletedDelegate == null)) {
                this.onDeleteStudentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteStudentCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteStudentDelegate, new object[] {
                        cne}, this.onEndDeleteStudentDelegate, this.onDeleteStudentCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TelerikSilverlightApp1.ServiceReference3.MyService.BegingetStudent(int cne, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetStudent(cne, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelerikSilverlightApp1.ServiceReference3.Etudiant TelerikSilverlightApp1.ServiceReference3.MyService.EndgetStudent(System.IAsyncResult result) {
            return base.Channel.EndgetStudent(result);
        }
        
        private System.IAsyncResult OnBegingetStudent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int cne = ((int)(inValues[0]));
            return ((TelerikSilverlightApp1.ServiceReference3.MyService)(this)).BegingetStudent(cne, callback, asyncState);
        }
        
        private object[] OnEndgetStudent(System.IAsyncResult result) {
            TelerikSilverlightApp1.ServiceReference3.Etudiant retVal = ((TelerikSilverlightApp1.ServiceReference3.MyService)(this)).EndgetStudent(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetStudentCompleted(object state) {
            if ((this.getStudentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getStudentCompleted(this, new getStudentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getStudentAsync(int cne) {
            this.getStudentAsync(cne, null);
        }
        
        public void getStudentAsync(int cne, object userState) {
            if ((this.onBegingetStudentDelegate == null)) {
                this.onBegingetStudentDelegate = new BeginOperationDelegate(this.OnBegingetStudent);
            }
            if ((this.onEndgetStudentDelegate == null)) {
                this.onEndgetStudentDelegate = new EndOperationDelegate(this.OnEndgetStudent);
            }
            if ((this.ongetStudentCompletedDelegate == null)) {
                this.ongetStudentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetStudentCompleted);
            }
            base.InvokeAsync(this.onBegingetStudentDelegate, new object[] {
                        cne}, this.onEndgetStudentDelegate, this.ongetStudentCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TelerikSilverlightApp1.ServiceReference3.MyService.BeginGetStudentsByFiliere(string filiere, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStudentsByFiliere(filiere, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Etudiant> TelerikSilverlightApp1.ServiceReference3.MyService.EndGetStudentsByFiliere(System.IAsyncResult result) {
            return base.Channel.EndGetStudentsByFiliere(result);
        }
        
        private System.IAsyncResult OnBeginGetStudentsByFiliere(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string filiere = ((string)(inValues[0]));
            return ((TelerikSilverlightApp1.ServiceReference3.MyService)(this)).BeginGetStudentsByFiliere(filiere, callback, asyncState);
        }
        
        private object[] OnEndGetStudentsByFiliere(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Etudiant> retVal = ((TelerikSilverlightApp1.ServiceReference3.MyService)(this)).EndGetStudentsByFiliere(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStudentsByFiliereCompleted(object state) {
            if ((this.GetStudentsByFiliereCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStudentsByFiliereCompleted(this, new GetStudentsByFiliereCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStudentsByFiliereAsync(string filiere) {
            this.GetStudentsByFiliereAsync(filiere, null);
        }
        
        public void GetStudentsByFiliereAsync(string filiere, object userState) {
            if ((this.onBeginGetStudentsByFiliereDelegate == null)) {
                this.onBeginGetStudentsByFiliereDelegate = new BeginOperationDelegate(this.OnBeginGetStudentsByFiliere);
            }
            if ((this.onEndGetStudentsByFiliereDelegate == null)) {
                this.onEndGetStudentsByFiliereDelegate = new EndOperationDelegate(this.OnEndGetStudentsByFiliere);
            }
            if ((this.onGetStudentsByFiliereCompletedDelegate == null)) {
                this.onGetStudentsByFiliereCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStudentsByFiliereCompleted);
            }
            base.InvokeAsync(this.onBeginGetStudentsByFiliereDelegate, new object[] {
                        filiere}, this.onEndGetStudentsByFiliereDelegate, this.onGetStudentsByFiliereCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TelerikSilverlightApp1.ServiceReference3.MyService.BeginGetAllFilieres(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllFilieres(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Filiere> TelerikSilverlightApp1.ServiceReference3.MyService.EndGetAllFilieres(System.IAsyncResult result) {
            return base.Channel.EndGetAllFilieres(result);
        }
        
        private System.IAsyncResult OnBeginGetAllFilieres(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TelerikSilverlightApp1.ServiceReference3.MyService)(this)).BeginGetAllFilieres(callback, asyncState);
        }
        
        private object[] OnEndGetAllFilieres(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Filiere> retVal = ((TelerikSilverlightApp1.ServiceReference3.MyService)(this)).EndGetAllFilieres(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllFilieresCompleted(object state) {
            if ((this.GetAllFilieresCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllFilieresCompleted(this, new GetAllFilieresCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllFilieresAsync() {
            this.GetAllFilieresAsync(null);
        }
        
        public void GetAllFilieresAsync(object userState) {
            if ((this.onBeginGetAllFilieresDelegate == null)) {
                this.onBeginGetAllFilieresDelegate = new BeginOperationDelegate(this.OnBeginGetAllFilieres);
            }
            if ((this.onEndGetAllFilieresDelegate == null)) {
                this.onEndGetAllFilieresDelegate = new EndOperationDelegate(this.OnEndGetAllFilieres);
            }
            if ((this.onGetAllFilieresCompletedDelegate == null)) {
                this.onGetAllFilieresCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllFilieresCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllFilieresDelegate, null, this.onEndGetAllFilieresDelegate, this.onGetAllFilieresCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TelerikSilverlightApp1.ServiceReference3.MyService CreateChannel() {
            return new MyServiceClientChannel(this);
        }
        
        private class MyServiceClientChannel : ChannelBase<TelerikSilverlightApp1.ServiceReference3.MyService>, TelerikSilverlightApp1.ServiceReference3.MyService {
            
            public MyServiceClientChannel(System.ServiceModel.ClientBase<TelerikSilverlightApp1.ServiceReference3.MyService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetFilieresStats(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetFilieresStats", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.Dictionary<string, int> EndGetFilieresStats(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.Dictionary<string, int> _result = ((System.Collections.Generic.Dictionary<string, int>)(base.EndInvoke("GetFilieresStats", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllStudents(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllStudents", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<string>> EndGetAllStudents(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<string>> _result = ((System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<string>>)(base.EndInvoke("GetAllStudents", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteStudent(string cne, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cne;
                System.IAsyncResult _result = base.BeginInvoke("DeleteStudent", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeleteStudent(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeleteStudent", _args, result);
            }
            
            public System.IAsyncResult BegingetStudent(int cne, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cne;
                System.IAsyncResult _result = base.BeginInvoke("getStudent", _args, callback, asyncState);
                return _result;
            }
            
            public TelerikSilverlightApp1.ServiceReference3.Etudiant EndgetStudent(System.IAsyncResult result) {
                object[] _args = new object[0];
                TelerikSilverlightApp1.ServiceReference3.Etudiant _result = ((TelerikSilverlightApp1.ServiceReference3.Etudiant)(base.EndInvoke("getStudent", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStudentsByFiliere(string filiere, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = filiere;
                System.IAsyncResult _result = base.BeginInvoke("GetStudentsByFiliere", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Etudiant> EndGetStudentsByFiliere(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Etudiant> _result = ((System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Etudiant>)(base.EndInvoke("GetStudentsByFiliere", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllFilieres(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllFilieres", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Filiere> EndGetAllFilieres(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Filiere> _result = ((System.Collections.ObjectModel.ObservableCollection<TelerikSilverlightApp1.ServiceReference3.Filiere>)(base.EndInvoke("GetAllFilieres", _args, result)));
                return _result;
            }
        }
    }
}
